//! Local Agent Rule / memory payloads (legacy cloud "AIFact").
//!
//! These types intentionally do not depend on cloud ownership, GraphQL, server
//! auth, or hosted-service crates. Wire formats preserve the historical JSON
//! shape (`{"memory":{...}}`) so on-disk and in-memory rules continue to
//! round-trip. Cloud wrappers live in `cloud_object_models` until that stack
//! is deleted (#41).

use std::fmt::Display;

use serde::{Deserialize, Serialize};

/// A local Agent Rule payload (currently only memory/rules text).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum AIFact {
    #[serde(rename = "memory")]
    Memory(AIMemory),
}

/// Opaque id for suggested objects, used to suppress re-surfacing the same
/// suggestion after the user accepted or dismissed it.
///
/// Historically also used for telemetry correlation between a suggestion and a
/// stored cloud object; ZYH keeps the id only for local suggestion state.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
pub struct SuggestedLoggingId(String);

impl Display for SuggestedLoggingId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl From<String> for SuggestedLoggingId {
    fn from(value: String) -> Self {
        Self(value)
    }
}

impl SuggestedLoggingId {
    pub fn as_str(&self) -> &str {
        &self.0
    }

    pub fn into_string(self) -> String {
        self.0
    }
}

/// Memory / rule body stored under the `memory` AIFact variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AIMemory {
    #[serde(default)]
    pub name: Option<String>,
    pub content: String,
    // Deprecated: This field is no longer used and will be removed in the future.
    #[serde(default)]
    pub is_autogenerated: bool,
    /// If this rule was created from a suggested rule, record the suggestion's
    /// logging_id so we can suppress re-surfacing the same suggestion.
    #[serde(default)]
    pub suggested_logging_id: Option<SuggestedLoggingId>,
}

impl AIFact {
    pub fn is_memory(&self) -> bool {
        matches!(self, AIFact::Memory { .. })
    }

    /// Borrow the memory body when this fact is a memory/rule.
    pub fn as_memory(&self) -> Option<&AIMemory> {
        match self {
            AIFact::Memory(memory) => Some(memory),
        }
    }
}

#[cfg(test)]
#[path = "ai_fact_tests.rs"]
mod tests;
