use super::{AIFact, AIMemory, SuggestedLoggingId};

#[test]
fn memory_fact_round_trips_historical_json_shape() {
    let fact = AIFact::Memory(AIMemory {
        name: Some("style".to_string()),
        content: "Prefer short functions".to_string(),
        is_autogenerated: false,
        suggested_logging_id: Some(SuggestedLoggingId::from("sug-1".to_string())),
    });

    let json = serde_json::to_value(&fact).expect("serialize");
    assert_eq!(
        json,
        serde_json::json!({
            "memory": {
                "name": "style",
                "content": "Prefer short functions",
                "is_autogenerated": false,
                "suggested_logging_id": "sug-1",
            }
        })
    );

    let parsed: AIFact = serde_json::from_value(json).expect("deserialize");
    assert_eq!(parsed, fact);
    assert!(parsed.is_memory());
    assert_eq!(
        parsed.as_memory().map(|m| m.content.as_str()),
        Some("Prefer short functions")
    );
}

#[test]
fn memory_fact_defaults_optional_fields() {
    let parsed: AIFact = serde_json::from_str(r#"{"memory":{"content":"only content required"}}"#)
        .expect("deserialize minimal memory");

    match parsed {
        AIFact::Memory(memory) => {
            assert_eq!(memory.content, "only content required");
            assert!(memory.name.is_none());
            assert!(!memory.is_autogenerated);
            assert!(memory.suggested_logging_id.is_none());
        }
    }
}

#[test]
fn suggested_logging_id_display_and_from_string() {
    let id = SuggestedLoggingId::from("abc".to_string());
    assert_eq!(id.to_string(), "abc");
    assert_eq!(id.as_str(), "abc");
    assert_eq!(id.into_string(), "abc");
}
